{
 "title": "Highloadcup",
 "time": { "from": "2021-03-24T11:19:00.788Z", "to": "2021-03-24T11:30:09.176Z" },
 "templating": {
  "list": [
   { "name": "sessionId", "label": "sessionId", "query": { "query": "label_values(tankId)" } }
  ]
 },
 "panels": [
  {
   "title": "Cash count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(task_openapi_http_request_duration_seconds_count{tankId=\"$sessionId\", method=\"POST\", resource=\"cash\"}[15s])",
     "legendFormat": "cash"
    }
   ]
  },
  {
   "title": "Cash sum",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(task_openapi_http_request_duration_seconds_sum{tankId=\"$sessionId\", method=\"POST\", resource=\"cash\"}[15s])",
     "legendFormat": "cash"
    }
   ]
  },
  {
   "title": "Dig count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(task_openapi_http_request_duration_seconds_count{tankId=\"$sessionId\", method=\"POST\", resource=\"dig\"}[15s])",
     "legendFormat": "dig"
    }
   ]
  },
  {
   "title": "Dig sum",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(task_openapi_http_request_duration_seconds_sum{tankId=\"$sessionId\", method=\"POST\", resource=\"dig\"}[15s])",
     "legendFormat": "dig"
    }
   ]
  },
  {
   "title": "License count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(task_openapi_http_request_duration_seconds_count{tankId=\"$sessionId\", method=\"POST\", resource=\"licenses\"}[15s])",
     "legendFormat": "licenses"
    }
   ]
  },
  {
   "title": "License duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(task_openapi_http_request_duration_seconds_sum{tankId=\"$sessionId\", method=\"POST\", resource=\"licenses\"}[15s])",
     "legendFormat": "licenses"
    }
   ]
  }
 ]
}