FROM ubuntu:20.10 as build

RUN apt-get update && apt-get install -y \
    g++ cmake libgoogle-perftools-dev rapidjson-dev libcurl4-openssl-dev

WORKDIR /app

COPY src ./src
COPY CMakeLists.txt .

ARG build_type
ARG commit_hash

RUN mkdir -p build/$build_type
RUN ls build/

RUN touch build.sh && chmod a+x build.sh
RUN (\
    echo '#!/bin/bash';\
    echo cmake -S . -B build/$build_type -DBUILD_TYPE=$build_type -DCOMMIT_HASH=$commit_hash; \
    echo cmake --build build/$build_type -j 7 --target highloadcup2021; \
    echo cp build/$build_type/highloadcup2021 build/; \
) > build.sh

RUN cat build.sh

RUN touch test.sh && chmod a+x test.sh
RUN (\
    echo '#!/bin/bash';\
    echo cmake -S . -B build/$build_type -DBUILD_TYPE=$build_type -DCOMMIT_HASH=$commit_hash; \
    echo cmake --build build/$build_type -j 7 --target highloadcup2021_tests; \
    echo ./build/$build_type/highloadcup2021_tests; \
) > test.sh

RUN cat test.sh

COPY src ./src
COPY CMakeLists.txt .

CMD ["./build.sh"]
